name: ci-short-url-workflow
on: 
  push:
      branches: 
        - main
  pull_request:
      branches: 
        - main
jobs:
    check-application:
        strategy:
            matrix:
                node-version: [24.x]
        runs-on: ubuntu-latest
        env:
          DATABASE_URL: postgres://postgres:docker@pg:5432/db
          REDIS_URL: redis://redis:6379
          JWT_SECRET: secret
          RESET_PASSWORD_SECRET: reset_password_secret
          SENTRY_DSN: 
          SENTRY_ENABLED: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run test:unit
            - run: npm run lint
            - run: npm run build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: pedronx/short-url:latest
      
